### ISSUE TITLE
Does granian support SIGHUP to reload config and restart workers?

### ISSUE THREAD

**Issue by ifduyue** [emmett-framework/granian#100]
Hello,

Like what gunicorn does

<img width="743" alt="image" src="https://github.com/emmett-framework/granian/assets/568900/b7d6cba9-82f6-41d7-9943-6b14044af286">

**Comment by gi0baro** [comment]
@ifduyue at present time, nope

**Comment by elbaro** [comment]
+1 feature request for this.

--reload is useful for development, but when updating a large codebase in the prod, Granian shouldn't react to a single file change but should be manually reloaded by the user.

Also it should keep the number of available workers to N~N+1 for graceful reload. spawn 1 new process, kill 1 old process, spawn 1 new, and so on.
