### ISSUE TITLE
Flag to disable the logging

### ISSUE THREAD

**Issue by Aeron** [emmett-framework/granian#101]
Hey, the superb library you created here. I appreciate the effort very much.

Yet I am curious if there is a way to remove Granian logging, in case I like to control logging myself on the application level.

The only way I was quick to think of is to trick the `log_dictconfig` by supplying the `{"root": {}}` dictionary. (Yes, I am another guy who loves to run Granian programmatically, not by CLI.)

Will it be simpler to provide a separate CLI flag and a constructor argument for that?

**Comment by gi0baro** [comment]
Hi @Aeron, sorry for the late reply, I was AFK.

As of today there's no quick way to do so. Probably an additional flag for this would be the best option. You might want to open a PR for this?

**Comment by Aeron** [comment]
If you’re okay with the proposal, then sure, I’ll gladly look into it when I have a moment 👍

**Comment by gi0baro** [comment]
> If you’re okay with the proposal, then sure, I’ll gladly look into it when I have a moment 👍

Sure thing! ❤️
