### ISSUE TITLE
reload bug

### ISSUE THREAD

**Issue by vitalik** [emmett-framework/granian#135]
see video

https://github.com/emmett-framework/granian/assets/95222/9785bcc5-f494-44e9-9dc1-a81bc946b09c

**Comment by gi0baro** [comment]
@vitalik I highly suspect this is related to Hyper, and it seems also to be fixed in the upstream version (ref: https://github.com/hyperium/hyper/pull/3261).
Unfortunately it also seems they didn't backported the fix to the current version, thus I think this will be solved once #25 is done.

**Comment by vitalik** [comment]
maybe for now have some workaround - like start a new process - one with watcher, one with socket - and watcher should kill old socket-process and start new one ?

**Comment by vitalik** [comment]
@gi0baro - but what I mean is kill with sigkill  (as sigterm probably waits for some loop signal)
