### ISSUE TITLE
Instructions to run django application on ubuntu production server. 

### ISSUE THREAD

**Issue by xeroticikot** [emmett-framework/granian#138]
I'm trying to use granian for production deployment of django application, but unable to do so due to lack of documentation. Care to provide some instruction for django runtime?

**Comment by gi0baro** [comment]
@xeroticikot there's no difference to any other ASGI/WSGI application and/or server.

Something like this should just work:

```
granian --interface asgi myproject.asgi:application
granian --interface wsgi myproject.wsgi:application
```

**Comment by gi0baro** [comment]
@xeroticikot you can't. Granian doesn't support unix socket files bindings.

FYI, you can always check all the available options in the README and with `granian --help`

**Comment by madhanrajan** [comment]
this is not working on heroku, idk why
