### ISSUE TITLE
setup logic is executed multiple times

### ISSUE THREAD

**Issue by GlenDC** [emmett-framework/granian#142]
- when I start up it already is running more then once
- when I change a file and it reloads (using `--reload`) it also runs it again

I run my FastAPI using:

```
granian --interface asgi app/main:app --host 127.0.0.1 --port 8080 --reload
```

And it's declared in that main file.

In there is a thing called `foo.setup()` related to my logging infrastructure.

It is supposed to only run once ever, but seems that it is running over and over again.
Is there a way for me to declare it in that main file so that this kind of stuff is only ever run the very first time that the program is loaded?

It's not critical I think, so I can probably ignore it, but dunno, would prefer to have this as clean as possible.

**Comment by stumpylog** [comment]
You might be looking for https://fastapi.tiangolo.com/advanced/events/#lifespan

**Comment by gi0baro** [comment]
@GlenDC whenever granian tracks a change in your codebase it respawns the worker(s). Every worker is a separate process with it's own Python interpreter, and thus your code gets reimported from scratch. This also means your setup is actually run only when your code gets loaded, it just gets loaded every reload.

As soon as your code doesn't need singletons in multiprocessing paradigm, you can safely ignore the thing ;)

**Comment by GlenDC** [comment]
Thanks both. This does make it work for me :) Awesome!
