### ISSUE TITLE
Implement a timeout

### ISSUE THREAD

**Issue by jefer94** [emmett-framework/granian#177]
Something like `--timeout 30`, I'm writing a benchmark and I need to set this value

**Comment by gi0baro** [comment]
🤔 a timeout on what? can you be more specific?
Also, if I'd implementing a benchmark, and we're talking about a timeout on request time, I'd implement it on the client side, not on the server. Having a timeout on the server would produce false results in a benchmark IMHO.

**Comment by jefer94** [comment]
For handling the requests timeouts, I have something like

```bash
echo "# Django Workers" > $FILE

sudo fuser -k $PORT/tcp
gunicorn mysite.asgi --timeout $TIMEOUT --workers $THREADS --worker-class uvicorn.workers.UvicornWorker & echo "starting server..."
sleep $SLEEP_TIME
echo "## ASGI Gunicorn Uvicorn" >> $FILE
bench

sudo fuser -k $PORT/tcp
granian --interface asgi mysite.asgi:application --port $PORT --workers $THREADS --loop asyncio --no-opt & echo "starting server..."
sleep $SLEEP_TIME
echo "## Granian Asyncio" >> $FILE
bench

sudo fuser -k $PORT/tcp
granian --interface asgi mysite.asgi:application --port $PORT --workers $THREADS --loop uvloop --no-opt & echo "starting server..."
sleep $SLEEP_TIME
echo "## Granian uvloop" >> $FILE
bench

sudo fuser -k $PORT/tcp
```

And I thought if each server would have different timeout it should affect the results, and I'm working over Heroku, it has a request timeout of 30 seconds

My benchmark is not so realistic, I think but cover a lot of common tasks
- benchmark: https://github.com/breatheco-de/apiv2/blob/main/benchmarks/django-workers/bench.sh
- urls: https://github.com/breatheco-de/apiv2/blob/main/benchmarks/django-workers/mysite/urls.py
- views: https://github.com/breatheco-de/apiv2/blob/main/benchmarks/django-workers/myapp/views.py

I got good results, but I could not get any good results for AIOHTTP or HTTPX test, so I think maybe the default request timeout should affect to Granian result

**Comment by jefer94** [comment]
And it appears even with `--no-opt`, apparently it is not handling the requests timeout, and it should penalize the results for all the output it is generating in the console

```bash
[WARNING] Application callable raised an exception
Task exception was never retrieved
future: <Task finished name='Task-55077' coro=<future_watcher_wrapper.<locals>.future_watcher() done, defined at /home/jefer/dev/work/apiv2/benchmarks/django-workers/.venv/lib/python3.11/site-packages/granian/_futures.py:2> exception=TypeError('PyFutureAwaitable.cancel() takes no arguments (1 given)')>
Traceback (most recent call last):
  File "/home/jefer/dev/work/apiv2/benchmarks/django-workers/.venv/lib/python3.11/site-packages/granian/_futures.py", line 4, in future_watcher
    await inner(watcher.scope, watcher.proto)
  File "/home/jefer/dev/work/apiv2/benchmarks/django-workers/.venv/lib/python3.11/site-packages/django/core/handlers/asgi.py", line 170, in __call__
    await self.handle(scope, receive, send)
  File "/home/jefer/dev/work/apiv2/benchmarks/django-workers/.venv/lib/python3.11/site-packages/django/core/handlers/asgi.py", line 218, in handle
    task.cancel()
TypeError: PyFutureAwaitable.cancel() takes no arguments (1 given)
Task exception was never retrieved
future: <Task finished name='Task-55434' coro=<ASGIHandler.listen_for_disconnect() done, defined at /home/jefer/dev/work/apiv2/benchmarks/django-workers/.venv/lib/python3.11/site-packages/django/core/handlers/asgi.py:226> exception=RequestAborted()>
Traceback (most recent call last):
  File "/home/jefer/dev/work/apiv2/benchmarks/django-workers/.venv/lib/python3.11/site-packages/django/core/handlers/asgi.py", line 230, in listen_for_disconnect
    raise RequestAborted()
django.core.exceptions.RequestAborted
```

**Comment by gi0baro** [comment]
@jefer94 1.0 added the proper code to handle `cancel` calls on `PyFutureAwaitable`, this should solve your issue.

As for the timeout thing, I'm still not convinced Granian should implement this and leave it to the application/framework.

**Comment by jefer94** [comment]
I will make an endpoint in Heroku with an `asyncio.sleep(40); print('somebody')` on Wednesday to see how them interact

**Comment by JaimeOnaindia** [comment]
A timeout would be nice, timeout with the proxy, nging or whatever, just like unicorn and gunicorn

**Comment by gi0baro** [comment]
Closing this as stale

**Comment by Object905** [comment]
It would be really nice to have to kill "misbehaving" workers.
I've started using granian for one "legacy" service (in wsgi mode) and faced issue when some requests are hanging - deadlocking in DB transaction on hot table. Because of this postgres spikes in memory usage when this happens. After app is restarted - everything is ok. This deadlock happens very rarely and is hard to debug - so seems like timeouts are best solution for this.

**Comment by gi0baro** [comment]
> faced issue when some requests are hanging - deadlocking in DB transaction on hot table. Because of this postgres spikes in memory usage when this happens. After app is restarted - everything is ok. This deadlock happens very rarely and is hard to debug - so seems like timeouts are best solution for this.

To me it sounds like you actually want statement execution timeouts and lock acquire timeouts in postgres and thus deal with the relevant errors in the Python app.
There's no way for Granian in WSGI to stop postgresql queries.

**Comment by Object905** [comment]
Yes, surely it would be better to fix that in code.
But it's legacy that stinks 😃. I was unable to pinpoint exactly why/where it happens. 
Global timeouts will cause other stuff to break for sure, but I'll try them out, thanks for the tip.

In that case I would be fine if hanging worker was killed altogether, so rolled back to gunicorn with timeouts for now because of that.

**Comment by edmorley** [comment]
We would also find a request timeout extremely useful. (I was going to file a new issue for this, but found this one.)

I agree that in an ideal app, all blocking operations would have correctly set timeouts, however, many libraries/frameworks default to no timeouts (including several popular HTTP clients), making it's extremely easy for end developers of an app to inadvertently end up with indefinitely blocking operations in some edge cases. Without a "timeout of last resort" in the web server, these can permanently block use of a worker/thread until the server is restarted.

In addition, some platforms (such as Heroku) have their routing layer terminate requests over a certain max request time threshold (in the case of Heroku, 30 seconds), to ensure stable platform/app operation and to encourage app architecture best practices (like moving long running tasks out of the web server and to a background worker job instead). Once the routing layer has responded with an HTTP 503 to the client, there is no point wasting additional time on the request in the server - and by terminating the request early it makes it more likely that the server/app can recover when under load. 

Having a way to add a request timeout at the Granian level would help with both of these cases. It's also much easier to tell beginner end users to "use this web server with these best practice CLI arguments" (eg in a getting started guide) to help prevent them shooting themselves in the foot, than it is to expect every single one of them to remember to set app level timeouts for every blocking call from the outset :-)

Such a web server request timeout is possible when using gunicorn's sync worker type, via the `--timeout` argument.

**Comment by gi0baro** [comment]
> Such a web server request timeout is possible when using gunicorn's sync worker type, via the `--timeout` argument.

@edmorley that's because the `sync` worker in gunicorn is serial and processes requests 1 by 1 – which also why it shouldn't definitely be used in production environments.

> We would also find a request timeout extremely useful. (I was going to file a new issue for this, but found this one.)
> 
> Having a way to add a request timeout at the Granian level would help with both of these cases.

Based on your comment, I assume you're talking about WSGI applications. For that protocol **there's nothing Granian can do to enforce a timeout**, given the [lack of support](https://docs.rs/tokio/latest/tokio/task/index.html#cancellation) in `tokio` to cancel blocking operations:

> Be aware that tasks spawned using [spawn_blocking](https://docs.rs/tokio/latest/tokio/task/fn.spawn_blocking.html) cannot be aborted because they are not async. If you call abort on a spawn_blocking task, then this will not have any effect, and the task will continue running normally. The exception is if the task has not started running yet; in that case, calling abort may prevent the task from starting.

**Comment by edmorley** [comment]
> that's because the `sync` worker in gunicorn is serial and processes requests 1 by 1 – which also why it shouldn't definitely be used in production environments.

Yeah I'm very aware of the differences between the gunicorn workers types :-) I was giving this as an example of prior art that does allow for request timeouts. Also whilst I understand why you might say the `sync` worker type is not suitable for production - I feel that's a bit of an oversimplification - it can be suitable depending on the workload. (Though I would agree that the gunicorn docs oversell sync as a "probably good enough", when in fact it's not for many cases.)

> Based on your comment, I assume you're talking about WSGI applications. For that protocol **there's nothing Granian can do to enforce a timeout**, given the [lack of support](https://docs.rs/tokio/latest/tokio/task/index.html#cancellation) in `tokio` to cancel blocking operations:

Yes, WSGI. That's unfortunate that tokio's featureset doesn't make this possible.
