### ISSUE TITLE
Changed dependency structure of typer.

### ISSUE THREAD

**Issue by WAKayser** [emmett-framework/granian#261]
In the 0.12.0 release of typer tiangolo added extra additional dependencies that are installed unless a different package: "typer-slim" is being used.  

I am willing to provide a pull request to either update the dependencies to use the typer-slim package or alternatively I can also update the cli to use the underlying "click" library.

I am wondering what your stance is on this subject?

**Comment by gi0baro** [comment]
@WAKayser thank you for notifying this, I wasn't aware of the changes in Typer.

I'm actually more prone to release a patch version of Granian specifying a typer version < 0.12 to quickly address this, then a PR to drop typer and directly use `click` is more than welcome. I initially enjoyed typer just for the typing system, bit nowadays is become quite bloated in my opinion. Given the scope of Granian CLI, `click` would be definitely enough.

**Comment by bluetech** [comment]
In my opinion, even argparse is good enough, and it brings 0 dependencies :wink:
