### ISSUE TITLE
WSGI support is not spec conformant

### ISSUE THREAD

**Issue by apollo13** [emmett-framework/granian#29]
I wanted to give granian a try but WSGI support seems to be somewhat out of spec. Eg try:

```py
class Response:
    def __init__(self, parts):
        self.parts = parts

    def __iter__(self):
        return self

    def __next__(self):
        try:
            return self.parts.pop(0)
        except Exception:
            raise StopIteration

    def close(self):
        print("CLOSE CALLED")

def app(env, start_response):
    start_response('200 OK', [('Content-Type','text/html')])
    return Response([b"Hello", b" ", b"World"])
```

When running this, "Hello World" is returned properly but `.close()` is not called, see https://peps.python.org/pep-3333/#specification-details

**Comment by apollo13** [comment]
Using
```py
def app(env, start_response):
    start_response('200 OK', [('Content-Type','text/html'), ('Content-Length', '300')])
    return Response([b"Hello", b" ", b"World"])
```
should not hang the server, from https://peps.python.org/pep-3333/#handling-the-content-length-header
> Of course, if the application does not provide enough data to meet its stated Content-Length, the server should close the connection and log or otherwise report the error.

**Comment by apollo13** [comment]
`start_response` must return a `write(body_data)` callable, currently it returns None. Note that this mostly for older frameworks but  the spec still requires it afaik.

`start_response` also need to support an optional `exc_info`

**Comment by cirospaciari** [comment]
> I wanted to give granian a try but WSGI support seems to be somewhat out of spec. Eg try:
> 
> ```python
> class Response:
>     def __init__(self, parts):
>         self.parts = parts
> 
>     def __iter__(self):
>         return self
> 
>     def __next__(self):
>         try:
>             return self.parts.pop(0)
>         except Exception:
>             raise StopIteration
> 
>     def close(self):
>         print("CLOSE CALLED")
> 
> def app(env, start_response):
>     start_response('200 OK', [('Content-Type','text/html')])
>     return Response([b"Hello", b" ", b"World"])
> ```
> 
> When running this, "Hello World" is returned properly but `.close()` is not called, see https://peps.python.org/pep-3333/#specification-details

something like this will be in spec
```python3
app_iter = app.wsgi(environ, start_response)
try:
  for data in app_iter:
    send_data(data)
finally:
  if hasattr(app_iter, "close"):
    app_iter.close()
```

**Comment by apollo13** [comment]
If I am reading the code correctly, the whole response is also evaluated at once: https://github.com/emmett-framework/granian/blob/653f93a5e7d3547da38799d4d1db3dfba85af83c/granian/wsgi.py#L56

It would be better to write that back in a streaming fashion.

**Comment by cirospaciari** [comment]
> Using
> 
> ```python
> def app(env, start_response):
>     start_response('200 OK', [('Content-Type','text/html'), ('Content-Length', '300')])
>     return Response([b"Hello", b" ", b"World"])
> ```
> 
> should not hang the server, from https://peps.python.org/pep-3333/#handling-the-content-length-header
> 
> > Of course, if the application does not provide enough data to meet its stated Content-Length, the server should close the connection and log or otherwise report the error.

https://peps.python.org/pep-3333/#handling-the-content-length-header also says
> Under some circumstances, however, the server or gateway may be able to either generate a Content-Length header, or at least avoid the need to close the client connection. If the application does not call the write() callable, and returns an iterable whose len() is 1, then the server can automatically determine Content-Length by taking the length of the first bytestring yielded by the iterable.

So I think you can also ignore Content-Length and automatically determine Content-Length, instead of closing the connection (with is a more pleasing experience for everyone I think)

**Comment by cirospaciari** [comment]
> No you shouldn't ignore the Content-Length header, if it is there you are supposed to use it. This is especially important for streaming larger respones where the iterable doesn't have a length of 1 (like in my example above). That said, my example is flawed since I do not implement support for `len()` at all -- that said I do not think that granian checks this anywhere currently.
> 
> My example about closing the connection was mostly about setting content length to 300 when the actual payload was "hello world" (ie shorter than 300). In this case the server has no good option but to close the connection since it would already have written "hello world" to the wire (in an ideal case) when it realizes that the rest of the data does not come.

You are right.

**Comment by gi0baro** [comment]
The issue with closing the response iterator is now fixed, so I'm closing this.

In regards to supporting iteration over responses, you can open up a dedicated issue.

**Comment by apollo13** [comment]
From a quick look I do not think your fix works. `b"".join(rv)` could throw an exception and if that happens you are no calling close. If I remember the spec correctly you must call close even in case of errors.
