### ISSUE TITLE
Problem configuring access log using a log config file

### ISSUE THREAD

**Issue by Isildur981** [emmett-framework/granian#310]
Thanks for adding access logging to Granian.  I have been trying to configure the access log format using a json config file, but have been unable to do so successfully.  I have been using a config file to change the default log format for a while.  After studying the changes to the log.py file I updated my log_config.json file, but receive a logging error whenever I load a web page.  I've attached my json config file.  

To keep things simple I only have the addr atom in my config file, but I would add others once I get this working.  The error displayed is "KeyError: 'addr'.  A little farther down  "ValueError: Formatting field not found in record: 'addr'"  is shown.  At the end of the traceback message the following two lines are displayed:

`Message: '[%(time)s] %(addr)s - "%(method)s %(path)s %(protocol)s" %(status)d %(dt_ms).3f'

Arguments: {'addr': '127.0.0.1', 'time': '2024-05-29 09:35:05 -0500', 'dt_ms': 48.99859428405762, 'status': 200, 'path': '/Folder/MakePage', 'query_string': b'', 'method': 'GET', 'scheme': 'http', 'protocol': 'HTTP/1.1'}`

The arguments dictionary has the addr key, so I'm confused by the error message.  I've probably got something misconfigured in my config file, but I've worked on this for a couple of hours, and haven't been able to solve the problem.  If the entire traceback message is needed, I can supply it.  Any suggestions for what I need to change/fix are appreciated.  Thanks. 

[log_config.json](https://github.com/emmett-framework/granian/files/15486364/log_config.json)

**Comment by gi0baro** [comment]
You should use `--access-log-fmt` to select which atoms to apply. So given your configuration, probably your `log_config.json` should look like this for access:

```json
{
    "formatters": {
        "access": {
            "fmt": "%(asctime)s.%(msecs)03d] %(message)s",
        }
    }
}
```

and then you should pass this to granian: `--access-log-fmt '%(addr)s'`

**Comment by Isildur981** [comment]
Thanks for the response.  I probably won't have a chance to try out your suggestion until tomorrow or Friday.

**Comment by Isildur981** [comment]
I was able to get the access log formatted the way I wanted based off of your suggestion.  Thanks for the help.  I'll close the issue if I have the permissions necessary.
