### ISSUE TITLE
Implement --pid

### ISSUE THREAD

**Issue by aersam** [emmett-framework/granian#319]
Hi guys

Thanks for having created granian, it's a great thing!

There's of course always potential for improvement, here's something I miss from gunicorn:

- In gunicorn you can pass [--pid](https://docs.gunicorn.org/en/stable/settings.html#pidfile) which will write the gunicorn's pid (not the workers) into a simple file
- Using that PID you can then send signals to the Main process, see https://docs.gunicorn.org/en/stable/signals.html
Most important one is probably `HUP` which will do a restart of the workers, which is very nice

Not sure I find the time to implement this, especially as I'm not a UNIX pro, but I could give it a try if no one wants to do this

**Comment by gi0baro** [comment]
Just to clarify: Granian already supports `HUP` signal to gracefully restart workers.

The `--pid` option sounds legit and easy to implement, targeting this for next minor.
