### ISSUE TITLE
jemalloc and freebsd

### ISSUE THREAD

**Issue by josejachuf** [emmett-framework/granian#329]
Hi @gi0baro 
This issue occurs on FreeBSD with the specified versions of Emmett and Granian. I understand that the error is not with Emmett but with Granian in the latest version due to the use of jemalloc.

> pip list | grep emmett
> emmett             2.5.11
> emmett-crypto      0.6.0
> emmett-rest        1.5.2

```
# emmett -a app migrations generate -m "first migration"
<jemalloc>: Error in dlsym(RTLD_NEXT, "pthread_create")
Abort trap
```

You can find more details on jemalloc here:
[FreeBSD jemalloc man page](https://man.freebsd.org/cgi/man.cgi?jemalloc)

The tikv-jemallocator should be supported on FreeBSD:
[GitHub search for tikv-jemallocator FreeBSD support](https://github.com/search?q=repo%3Atikv%2Fjemallocator%20freebsd&type=code)

On FreeBSD, orjson, emmett-crypto, granian, and all Rust libraries are compiled when installed with pip. Am I missing any environment variables?

**Comment by gi0baro** [comment]
It seems we're not alone on this https://github.com/pola-rs/polars/issues/15542

I'm not sure what options we have on this other than disabling jemalloc/use mimalloc on freebsd.
Just to confirm: if you pin Emmett to 2.5.9 (which should use Granian ~1.0.x, and thus mimalloc) does it work?

**Comment by josejachuf** [comment]
I was going to tell you that the same thing happens in Polar



> Just to confirm: if you pin Emmett to 2.5.9 (which should use Granian ~1.0.x, and thus mimalloc) does it work?

Yes, its works fine

**Comment by gi0baro** [comment]
@josejachuf Granian 1.4.4 will have this fixed

**Comment by josejachuf** [comment]
Thanks @gi0baro !

**Comment by josejachuf** [comment]
works fine:
```
# emmett shell
Python 3.11.9 (main, Apr  9 2024, 01:10:47) [Clang 16.0.6 (https://github.com/llvm/llvm-project.git llvmorg-16.0.6-0-g7cbf1a on freebsd14
Emmett 2.5.11 shell on app: app
>>>
```
