### ISSUE TITLE
WSGI response iterator lagging with Flask when mimetype="text/event-stream"

### ISSUE THREAD

**Issue by CNFeffery** [emmett-framework/granian#334]
reproduce demo code:

```python
import time
from flask import Flask, Response

app = Flask(__name__)


@app.route("/stream-demo")
def stream_demo():
    def _stream():
        while True:
            time.sleep(0.1)
            yield "data: %s\n\n" % str(time.time())

    return Response(_stream(), mimetype="text/event-stream")


if __name__ == "__main__":
    app.run(debug=True)
```

raw Flask run:

![flask_raw_run](https://github.com/emmett-framework/granian/assets/49147660/e3872a93-0656-444f-a68a-be6ad51c6c8c)

run with granian:

```bash
granian --interface wsgi app:app
```
![flask_with_granian](https://github.com/emmett-framework/granian/assets/49147660/f56614ea-ba8b-422d-a487-4d3d2efffbb1)

**Comment by CNFeffery** [comment]
@gi0baro Windows 11, Python 3.9.19, granian 1.4.2, Flask 3.0.3.

**Comment by gi0baro** [comment]
@CNFeffery can you please try the same with 1.4.4 and verify the issue is still there?

**Comment by CNFeffery** [comment]
@gi0baro has the same status with 1.4.4, the stream response does not return data step by step smoothly.
