### ISSUE TITLE
WSGI headers with accented characters are not passed to the app

### ISSUE THREAD

**Issue by Kumzy** [emmett-framework/granian#335]
Hello,

I am using nginx + granian to serve my app but I found that a headers value containing an accent is not passed to the app:
`search_term: levé`

Python 3.11.9
Ubuntu 22.04
Flask 2.3.2
Granian 1.4.0

My command in systemd

`/api/venv/bin/granian --host 127.0.0.1 --port 8000 --no-ws --interface wsgi --workers 1 --threads 8 run_wsgi:app`*

Then the nginx has a proxy_pass to `http://127.0.0.1:8000`

When using gunicorn, the headers is passed correctly

Edit: Tested with 1.4.4 and same issue occurs

**Comment by gi0baro** [comment]
@Kumzy can you please provide a MRE including the request sent to the server?

**Comment by gi0baro** [comment]
Also, AFAIK the HTTP spec only allows ASCII characters in headers, and `é` it is not.. 🤔

**Comment by Kumzy** [comment]
Sorry I did not have time to create a MRE yet, it just that it's working with gunicorn. Maybe it's not allowed in the value of the headers, I did not check that

**Comment by gi0baro** [comment]
So, per spec (https://www.rfc-editor.org/rfc/rfc7230#section-3.2.4):
> Historically, HTTP has allowed field content with text in the
   ISO-8859-1 charset [[ISO-8859-1](https://www.rfc-editor.org/rfc/rfc7230#ref-ISO-8859-1)], supporting other charsets only
   through use of [[RFC2047](https://www.rfc-editor.org/rfc/rfc2047)] encoding.  In practice, most HTTP header
   field values use only a subset of the US-ASCII charset [[USASCII](https://www.rfc-editor.org/rfc/rfc7230#ref-USASCII)].
   Newly defined header fields SHOULD limit their field values to
   US-ASCII octets.  A recipient SHOULD treat other octets in field
   content (obs-text) as opaque data.

Thus, I don't think Granian should support non-ASCII characters decoding in WSGI protocol.
I'm closing this, feel free to open up a discussion about encoding support in comparison to other servers, and we'll se where that discussion land.

**Comment by Kumzy** [comment]
Yes, thank you. I will try to implement method to encode value correctly in my headers.
