### ISSUE TITLE
App factory

### ISSUE THREAD

**Issue by ZeN220** [emmett-framework/granian#338]
I didn't find any functionality similar to `--factory` from uvicorn. are there any plans to add such a thing? something like that:
```python
def create_app():
    app = MyAPP()
    return app
```
And running like this:
```shell
granian "module:create_app()"
```

**Comment by gi0baro** [comment]
As of today, there's no support for this in CLI. But you can run Granian via Python code and customise the `target_loader` parameter of `Granian.serve`.

Given your use-case, probably it's easier to write a `run.py` file which runs the factory, eg:

```python
from your_module import your_factory

app = your_factory()
```

and point Granian to `run:app`. It might also be worth checking #35.
