### ISSUE TITLE
Granian not working with fastapi FileResponse

### ISSUE THREAD

**Issue by vendari12** [emmett-framework/granian#373]
I am running fastapi on granian and am getting a 500 internal server error from this snippet. It works if i switch to uvicorn and/or gunicorn and it doesn't seem to log any exception to the terminal

`
async def get_single_image(
    session: AsyncSession, filename: str
) -> Union[FileResponse, StreamingResponse]:
    await logger.info(f"Getting single image for filename: {filename}")
    if filename.startswith("thumbnail"):
        return await get_image_thumbnail(session, filename)
    image = await Image.get_by_field(filename, "filename", session)
    if not image:
        await logger.warning(f"Image not found: filename {filename}", None)
        raise ObjectNotFound("Image does not exist")

    try:
        if not image.is_uploaded:
            if filename.endswith(BLOB_EXTENSION):
                return await serve_blob_files(
                    filename, Path(image.image_path(filename)), session, image
                )
            else:
                await logger.info(f"serving image file with name:{filename} ")
                return FileResponse(image.image_path(filename), filename=filename)
    except (RuntimeError, FileNotFoundError) as e:
        raise ObjectNotFound("Image does not exist on file system")
    except Exception as e:
        await logger.error("Something went wrong while serving files", e)

    await logger.info(f"Image found and served for filename: {filename}")
    return image.url
`

granian[reload]==1.5.2
python-multipart==0.0.7
fastapi==0.111.0
python3.11
Docker

Granian command 

`@cli.command()
def runserver():
    runner = Granian(
        "manage:app", "0.0.0.0", TRADO_MAIN_PORT, reload=True, log_level="error", interface="asgi"
    )
    runner.serve()`

N/B: The cli represents a typer cli instance

**Comment by vendari12** [comment]
I just downgraded my fastapi version to 1.108.0 and the issue went away

**Comment by gi0baro** [comment]
Duplicated of https://github.com/emmett-framework/granian/issues/320
