### ISSUE TITLE
Session Affinity / sticky sessions using Cookies

### ISSUE THREAD

**Issue by aersam** [emmett-framework/granian#390]
Many Python tools use some state per user in simple python dict's or similar. This makes it impossible to use multiple processes and so it scales not this good. For example, see: https://github.com/zauberzeug/nicegui/wiki/FAQs#how-to-avoid-the-reloading-because-handshake-failed-javascript-error-message-which-results-in-a-full-page-reload

It would be so great for granian to support some kind of session affinity, so that a cookie with some value would cause granian to send a request to always the same process. so an app could make the user stick on the same process (as long as it's not restarted). 

It's a feature usually only supported on more complex load balancers, gunicorn does not support it. But as it's really a common problem in python, it would be so great for granian to support it.

**Comment by jules-ch** [comment]
You can enable this behaviour on the reverse proxy or load balancer side.
