### ISSUE TITLE
WSGI sendfile support (`wsgi.file_wrapper`)

### ISSUE THREAD

**Issue by edmorley** [emmett-framework/granian#434]
Hi!

The WSGI spec includes support for optional platform-specific file handling support via `wsgi.file_wrapper`:
https://peps.python.org/pep-3333/#optional-platform-specific-file-handling

This can be used to improve performance of serving files - for example, by using `sendfile()` on Unix.

This is supported by gunicorn:
https://github.com/benoitc/gunicorn/blob/bacbf8aa5152b94e44aa5d2a94aeaf0318a85248/gunicorn/http/wsgi.py#L359-L390

...and when paired with eg [WhiteNoise](https://github.com/evansd/whitenoise/blob/a50121c637554ba3c7ce78d66122bd98c4313867/src/whitenoise/base.py#L90-L91), allows for Django static assets to be served in a fairly efficient way in environments where use of a separate nginx proxy is not possible or desired.

As such, it would be great if Granian's WSGI interface supported it too :-)

**Comment by gi0baro** [comment]
As of today there's no support for `sendfile(2)` in [tokio](https://github.com/tokio-rs/tokio) – and consequentially in [hyper](https://github.com/hyperium/hyper). Thus, even if Granian would provide a `file_wrapper` implementation, it won't have any noticeable performance benefit compared to reading the file in Python and iterate over its contents.

Note that this is also the same reason why ASGI zero copy send is marked as inapplicable in #93.

**Comment by edmorley** [comment]
@gi0baro Could you update the status of this issue to the new GitHub "wontfix" status, instead of the standard "closed"? It makes it clearer when viewing issues in eg search results that the feature wasn't implemented. See:
https://github.blog/changelog/2022-05-19-the-new-github-issues-may-19th-update/#%F0%9F%95%B5%F0%9F%8F%BD%E2%99%80%EF%B8%8F-issue-closed-reasons
