### ISSUE TITLE
asyncio - ERROR - Task was destroyed but it is pending!

### ISSUE THREAD

**Issue by rudcode** [emmett-framework/granian#436]
Hi, I encountered this error randomly but have no idea how to reproduce it intentionally. I use granian asgi with litestar. I use aiohttp for http client and aiomysql for mysql client.

With Uvicorn, I am not experiencing this issue.

```
[2024-11-20 06:55:28 +0700] 10.140.0.19 - "GET /address/by_id HTTP/1.1" 500 398.686
[ERROR] Application callable raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/granian/_futures.py", line 4, in future_watcher
    await inner(watcher.scope, watcher.proto)
GeneratorExit:
2024-11-20 06:55:29,180 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-553' coro=<future_watcher_wrapper.<locals>.future_watcher() done, defined at /usr/local/lib/python3.11/site-packages/granian/_futures.py:2> wait_for=<Future pending cb=[Task.task_wakeup()]>>
```

Has anyone else encountered this before?

**Comment by gi0baro** [comment]
Hi @rudcode, can you please also share:
- OS/arch
- Python version
- Loop used (asyncio or uvloop)

**Comment by rudcode** [comment]
Hi, I am using Ubuntu 22.04 with docker, here is my dockerfile

```
# Use an official Python runtime as a parent image
FROM ghcr.io/astral-sh/uv:python3.11-alpine

# Set the working directory to /app
WORKDIR /app

# Copy the requirements into the container at /app
COPY ./requirements.txt /app

# Install any needed packages specified in requirements.txt
RUN uv pip install --system -r requirements.txt

# Set the timezone to UTC (you can change 'UTC' to your desired timezone)
ENV TZ=Asia/Bangkok

# Copy the current directory contents into the container at /app
COPY . /app

# Make port 3090 available to the world outside this container
EXPOSE 3090

# Run app.py when the container launches
CMD ["granian", "--interface", "asgi", "app.main:app", \
    "--host", "0.0.0.0", "--port", "3090", "--access-log"]
```

**Comment by rudcode** [comment]
I tested using uvloop and asyncio, and both produce the same error.

**Comment by rudcode** [comment]
@gi0baro That was fast! Thank you

**Comment by rudcode** [comment]
Hi @gi0baro 

I have tested the latest version 1.6.4 but the error still persist.

```
[2024-11-27 07:59:18 +0700] 10.140.0.19 - "GET /address/by_id HTTP/1.1" 500 491.136
[ERROR] Application callable raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/granian/_futures.py", line 4, in future_watcher
    await inner(watcher.scope, watcher.proto)
GeneratorExit:
2024-11-27 07:59:18,549 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-4855' coro=<future_watcher_wrapper.<locals>.future_watcher() done, defined at /usr/local/lib/python3.11/site-packages/granian/_futures.py:2> wait_for=<Future pending cb=[Task.task_wakeup()]>>
```

**Comment by rudcode** [comment]
Hi @gi0baro, yes it only happens on the specific route GET /address/by_id, here is the snippet of the code. check_user function is calling external http api with aiohttp asyncclient, and controller_get_address function get the data from mysql database using aiomysql.

```
class AddressController(Controller):
    path = "/address"

    @get("/", exclude_from_auth=True)
    async def get_address_list(
        self,
        conn: Connection,
        request: Request,
    ) -> list[Address]:
        authorization = request.headers.get("authorization")
        if not authorization:
            raise NotAuthorizedException
        token = authorization[7:]
        user = await check_user(conn, token)
        return await controller_get_address_list(conn, user["chatkey"], user["bot_id"])

    @get("/by_id", exclude_from_auth=True)
    async def get_address(self, conn: Connection, request: Request) -> Address:
        authorization = request.headers.get("authorization")
        if not authorization:
            raise NotAuthorizedException
        token = authorization[7:]
        user = await check_user(conn, token)
        return await controller_get_address(conn, user["address_id"])

    @post("/", exclude_from_auth=True)
    async def create_address(
        self,
        conn: Connection,
        data: CreateAddressPayload,
        request: Request,
    ) -> CreateAddressResponse:
        authorization = request.headers.get("authorization")
        if not authorization:
            raise NotAuthorizedException
        token = authorization[7:]
        user = await check_user(conn, token)
        return await db_create_address(conn, data, user)
```

Can you guide me to debug this further? Is there any specific args to enable more debugging info? Right now I only use '--log-level debug' but still no additional information logged.

**Comment by rudcode** [comment]
Hi @gi0baro can you take a look at this commit https://github.com/rudcode/granian/commit/dd44d19cd26652fe30007e754c40ba7952ea4c93#diff-f3060fbe257ff798961acf50ffa1223fe01c309957d4b2b08e5ee213cdfb89a0R5 ? 

I think the reference should be kept in python code, so it doesn't get collected by the gc. I have tested this with version 1.6.3 for almost two hour and didn't get the error message.

**Comment by gi0baro** [comment]
> I think the reference should be kept in python code, so it doesn't get collected by the gc.

So, that's not how PyO3 works. Given the reference is kept on a `pyclass`, the interpreter shouldn't be able to GCollect the object behind that reference, unless that pyclass is deleted.
Which is kinda strange, given the object keeping the reference is the `watcher` one.

> I have tested this with version 1.6.3 for almost two hour and didn't get the error message.

I checked the code and while it might fix the issue, it feels like a lot of unnecessary bloat that might affect performance considerably. I still think this should be properly addressed solving the root issue.

In that sense, given in 1.7 that interaction will change radically, it would be nice if you can build Granian from #452 and test it in your environment to see if the new implementation also fix your issue.

**Comment by gi0baro** [comment]
I'm closing this since 1.7 is released.
@rudcode feel free to open a new issue if you experience similar issue with the new release.

**Comment by rudcode** [comment]
Hi @gi0baro, thank you will test it now with version 1.7.1.

**Comment by rudcode** [comment]
Hi @gi0baro, sorry for bothering again, but unfortunately with 1.7.1 the issue still persist.

```
[ERROR] Application callable raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/granian/_futures.py", line 11, in future_watcher
    await inner(watcher.scope, watcher.proto)
GeneratorExit:
2024-12-18 12:14:24,639 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1876' coro=<_future_watcher_wrapper.<locals>.future_watcher() done, defined at /usr/local/lib/python3.11/site-packages/granian/_futures.py:9> wait_for=<Future pending cb=[Task.task_wakeup()]>>
```

**Comment by gi0baro** [comment]
> Hi @gi0baro, sorry for bothering again, but unfortunately with 1.7.1 the issue still persist.

Makes sense, as with the addition of `--task-impl asyncio` the behavior is the same of 1.6.
Gonna plan some changes to store the task reference somewhere.

**Comment by rudcode** [comment]
Thank you @gi0baro
