### ISSUE TITLE
ImportError when run on Alpine Linux

### ISSUE THREAD

**Issue by Dominick-Peluso-Bose** [emmett-framework/granian#44]
I'm running into the following runtime error when I try to run a WSGI server using granian with an Alpine Linux docker base image:

```
Traceback (most recent call last):
  File "/usr/local/bin/granian", line 5, in <module>
    from granian import cli
  File "/usr/local/lib/python3.11/site-packages/granian/__init__.py", line 1, in <module>
    from .server import Granian
   File "/usr/local/lib/python3.11/site-packages/granian/server.py", line 12, in <module>
 ImportError: Error relocating /usr/local/lib/python3.11/site-packages/granian/_granian.cpython-311-x86_64-linux-musl.so: __stack_chk_fail: initial-exec TLS resolves to dynamic definition in /usr/local/lib/python3.11/site-packages/granian/_granian.cpython-311-x86_64-linux-musl.so
```

Does anyone know how to resolve this?

**Comment by gi0baro** [comment]
@Dominick-Peluso-Bose can you please check with different Python versions (3.9-3.10)? Sounds like something is wrong with the build system (maturin)..

**Comment by Dominick-Peluso-Bose** [comment]
It seems like it's the same deal with Python 3.10:

> Python version: 3.10.9
> OS version: Alpine Linux v3.17

```
 Traceback (most recent call last):
   File "/usr/local/bin/granian", line 5, in <module>
     from granian import cli
  File "/usr/local/lib/python3.10/site-packages/granian/__init__.py", line 1, in <module>
    from .server import Granian
 File "/usr/local/lib/python3.10/site-packages/granian/server.py", line 12, in <module>
    from ._granian import ASGIWorker, RSGIWorker, WSGIWorker
 ImportError: Error relocating /usr/local/lib/python3.10/site-packages/granian/_granian.cpython-310-x86_64-linux-gnu.so: __stack_chk_fail: initial-exec TLS resolves to dynamic definition in /usr/local/lib/python3.10/site-packages/granian/_granian.cpython-310-x86_64-linux-gnu.so
```

**Comment by gi0baro** [comment]
I gonna try upgrading maturin and run some tests.
In case that won't work this will need for sure a lot of debugging, probably with the support of PyO3 community..

**Comment by gi0baro** [comment]
@Dominick-Peluso-Bose upgrading maturin didn't solve the issue.

It seems we're not alone as `pydantic-core` seems to suffer from the same issue (https://github.com/pydantic/pydantic-core/issues/362).
I gonna stop releasing musl wheels so I can proceed with the next patch release, and dig into this more in the following days.
