### ISSUE TITLE
Enhancement: HTTP/2 Cleartext (`h2c`) support

### ISSUE THREAD

**Issue by cofin** [emmett-framework/granian#440]
Is it possible to enable HTTP/2 Cleartext support?  

I would like to enable HTTP2 in a Google Cloud Run service; it looks like `h2c` support is required for this.  Is this something that you think is feasible? 

[HTTP/2 in Cloud Run](https://cloud.google.com/run/docs/configuring/http2)

[HTTP2 FAQ](https://http2.github.io/faq/#can-i-implement-http2-without-implementing-http11)

**Comment by gi0baro** [comment]
Granian supports HTTP/2 without TLS as soon as you manually specify the `--http 2` option.
Granian won't ever support upgrades from HTTP/1.1 to HTTP/2 without alpn, though.

**Comment by cofin** [comment]
Thanks!  I guess I need to do some testing to see how far this functionality will get me.  I'll post any updates here.

**Comment by gi0baro** [comment]
I'm closing this as is currently supported. You can check it locally running Granian with `--http2` and using the test command GCP documentation provides:

```
curl -i --http2-prior-knowledge http://localhost:PORT
```

Feel free to comment again on this in case you find any issues, I'll reopen.
