### ISSUE TITLE
AsyncLibraryNotFoundError

### ISSUE THREAD

**Issue by jrlopes2005** [emmett-framework/granian#77]
Hi, im getting this issue in version 0.4.2.

asynclib_name = sniffio.current_async_library()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
raise AsyncLibraryNotFoundError(
 sniffio._impl.AsyncLibraryNotFoundError: unknown async library, or not in async context

Any ideas?

**Comment by gi0baro** [comment]
> Any ideas?

@jrlopes2005 not really without a complete stack trace/few more details, as I can't really tell what `sniffio` requires and/or in which moment of the application lifecycle you use it.

Also, since granian doesn't support `trio`, I'm not really sure what `sniffio` is needed for.

**Comment by jrlopes2005** [comment]
I'll get deeper into the issue and try do figure it out...i'll be back soon with news, i hope

**Comment by gi0baro** [comment]
@jrlopes2005 I have a colleague of mine experiencing the same issue with starlette.

Can you please upgrade to 0.4.3, run Granian with `--no-opt` option and check if it works?

**Comment by gi0baro** [comment]
Related to #80

**Comment by jrlopes2005** [comment]
Hi @gi0baro. 

I tested it and it works fine now (i changed the loop_opt parameter value to False in the Granian instance).

Thanks for your support.

**Comment by gi0baro** [comment]
@jrlopes2005 nice! I'm closing this since 0.5 now targets #86
