### ISSUE TITLE
Install error with pip

### ISSUE THREAD

**Issue by farizalmustaqim** [emmett-framework/granian#87]
![image](https://github.com/emmett-framework/granian/assets/54091450/a11b45d5-c5fd-4fa9-8b3c-c5ff944e2941)

**Comment by gi0baro** [comment]
@farizalmustaqim can you provide more details about this? eg. arch, OS, Python version..

**Comment by farizalmustaqim** [comment]
OS Linux, Python 3.6

**Comment by gi0baro** [comment]
@farizalmustaqim that's the issue, if you check [the README](https://github.com/emmett-framework/granian#project-status) granian requires Python >= 3.8

**Comment by farizalmustaqim** [comment]
Oh sorry and thanks you
